
mybatis:
  type-aliases-package: com.mpocket.disk.bean
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/disk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driverClass: com.mysql.jdbc.Driver
server:
  port: 8081
